function [A, B, C, D, ...
    xdot, y, x, u] = F16_Nguyen_linearize_plant(x0, u0, ...
    libalias, cplant, plant_properties)
%
% Evaluates the "F16_Nguyen_clib_linearize_plant" function,
% at the given "x0" (linearization states), and "u0"
% (linearization inputs).
%

% validate inputs
if isstruct(x0)
    x0 = cell2mat(struct2cell(x0));
end

if isstruct(u0)
    u0 = cell2mat(struct2cell(u0));
end


% do the thing
[err, A, B, C, D, ...
    xdot, y, x, u] = ...
    calllib(libalias, 'F16_Nguyen_clib_linearize_plant', ...
    zeros(plant_properties.num_states), plant_properties.num_states * plant_properties.num_states, ...
    zeros(plant_properties.num_states, plant_properties.num_inputs), plant_properties.num_states * plant_properties.num_inputs, ...
    zeros(plant_properties.num_outputs, plant_properties.num_states), plant_properties.num_outputs * plant_properties.num_states, ...
    zeros(plant_properties.num_outputs, plant_properties.num_inputs), plant_properties.num_outputs * plant_properties.num_inputs, ...
    zeros(plant_properties.num_states, 1), plant_properties.num_states, ...
    zeros(plant_properties.num_outputs, 1), plant_properties.num_outputs, ...
    zeros(plant_properties.num_states, 1), plant_properties.num_states, ...
    zeros(plant_properties.num_inputs, 1), plant_properties.num_inputs, ...
    cplant, ...
    x0, plant_properties.num_states, ...
    u0, plant_properties.num_inputs);

if err ~= 0
    error(['F16_Nguyen_linearize_plant:', ...
        ' "F16_Nguyen_clib_linearize_plant" returned an error (%d).'], err);

end

end